spring.application.name=sfg.springai.rag
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.model=text-embedding-3-small
sfg.springai-rag.vectorstore.vectorStorePath=/tmp/vectorstore.json
sfg.springai-rag.vectorstore.documentsToLoad=classpath:movies500.csv
